language: c
sudo: false

addons:
  apt:
    packages:
    - lua5.1
    - lua5.2
    - luajit

branches:
  only:
    - master

script:
  - lua5.1 tests/runner.lua
  - lua5.2 tests/runner.lua
  - luajit-2.0.0-beta9 tests/runner.lua
